💚 Add ci file v0.0.1
PANTS-GOORM/Batch pull request #3
Opened 2024-04-09 05:42 UTC by chickennight

add test and build yml

2024-04-09 06:11 UTC, TProgramer requested changes
변경해야 할 점들이 보여 리뷰 남깁니다

2024-04-09 06:11 UTC, TProgramer commented on .github/workflows/build_test.yml
> +        image: postgres:16.2-alpine3.18
알파인 사용에 문제 없는지 확인하셨나요?

2024-04-09 06:11 UTC, TProgramer commented on .github/workflows/build_test.yml
> +      - name: Set Secrets YML
secrets_be 레포에서 secret 값을 가져올 때, 특정 파일이나 디렉토리를 정해서 가져오는 것이 더 명확할 거 같습니다.

2024-04-09 06:11 UTC, TProgramer commented on .github/workflows/deploy.yml
> +          POSTGRES_PASSWORD: ddongpants
.github/workflows/build_test.yml 과 같은 이유로 확인 부탁드립니다.

2024-04-09 06:11 UTC, TProgramer commented on src/main/resources/application-prod.yml
> +      ddl-auto: update
prod 환경에서 예상치 못한 DB 변경을 막기위해, ddl-auto 옵션을 없애거나 validation 옵션으로 변경해주세요.

2024-04-09 06:13 UTC, chickennight commented on .github/workflows/build_test.yml
> +        image: postgres:16.2-alpine3.18
해당 버전은 도커에 있는 16.2중에 가장 이슈가 없는 버전입니다... 글고 도커 이미지로는 알파인만 있어유...

2024-04-09 06:14 UTC, chickennight commented on .github/workflows/build_test.yml
> +      - name: Set Secrets YML
옙 이건 실재로 시크릿이 생성되면 특정해서 가져오겠습니다

2024-04-09 06:32 UTC, chickennight commented on src/main/resources/application-prod.yml
> +      ddl-auto: update
수정했습니다

2024-04-09 06:32 UTC, chickennight commented on .github/workflows/deploy.yml
> +          POSTGRES_PASSWORD: ddongpants
!

2024-04-12 03:02 UTC, TProgramer approved these changes
변경 사항 적용 확인했습니다

2024-04-12 03:02 UTC, merged